### ISSUE TITLE
Problem compiling the project

### ISSUE THREAD

**Issue by osmadja** [moppletop/YeeLight-API#5]
<img width="1060" alt="Screenshot 2023-03-11 at 21 09 00" src="https://user-images.githubusercontent.com/620283/224517113-ce78fc8b-ef2e-4b92-98d5-49ab4b55f8ff.png">
Hello, nice project. 

But I'm having several problems to compile the project. Example above. Seems to be associated to lombok annotation. 

I think I'm missing a step. Could you help me ?

Thanks

**Comment by moppletop** [comment]
Hello, The issue is likely because you haven't got lombok configured to work within your IDE. I think by the screenshot you're using eclipse, [this should](https://www.baeldung.com/lombok-ide) be able to help you.

**Comment by osmadja** [comment]
Thank you very much

**Comment by osmadja** [comment]
It is much better now. But there is still one error 
<img width="910" alt="Screenshot 2023-03-11 at 22 51 02" src="https://user-images.githubusercontent.com/620283/224519827-9255bdb2-6f5c-4c1a-9aa6-f563665c90ea.png">

It did not find the constructor :  The constructor YeeApiImpl(YeeManager) is undefined

**Comment by osmadja** [comment]
I created the constructor in the YeeApiImpl class:

    public YeeApiImpl(YeeManager manager) {
    	this.manager = manager;
    }

Then I executed the DiscoveryTest class and got : 


Exception in thread "Thread-1" java.net.SocketException: Socket closed
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:252)
	at java.base/java.net.DatagramSocket.receive(DatagramSocket.java:700)
	at com.moppletop.yeelight.api.util.TestUDPServer.run(TestUDPServer.java:33)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.nio.channels.AsynchronousCloseException
	at java.base/sun.nio.ch.DatagramChannelImpl.endRead(DatagramChannelImpl.java:523)
	at java.base/sun.nio.ch.DatagramChannelImpl.trustedBlockingReceive(DatagramChannelImpl.java:677)
	at java.base/sun.nio.ch.DatagramChannelImpl.blockingReceive(DatagramChannelImpl.java:635)
	at java.base/sun.nio.ch.DatagramSocketAdaptor.receive(DatagramSocketAdaptor.java:240)
	... 3 more

**Comment by moppletop** [comment]
I've checked on my local copy. The constructor issue is another Lombok problem. The socket issue running the tests would be another thing I'd need more info on to debug. I know the library works in it's current state as I've others run it in the past.
